<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.15" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.15" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroManage.BookingManagement.Application\AeroManage.BookingManagement.Application.csproj" />
    <ProjectReference Include="..\AeroManage.BookingManagement.Infrastructure\AeroManage.BookingManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\AeroManage.FlightManagement.Application\AeroManage.FlightManagement.Application.csproj" />
    <ProjectReference Include="..\AeroManage.FlightManagement.Infrastructure\AeroManage.FlightManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\AeroManage.Shared\AeroManage.Shared.csproj" />
    <ProjectReference Include="..\AeroMange.UserManagement.Application\AeroMange.UserManagement.Application.csproj" />
    <ProjectReference Include="..\AeroMange.UserManagement.Infrastructure\AeroMange.UserManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
